import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'language_selection': 'Language Selection',
      'select_language': 'Please select your language',
      'next': 'Next',
      'home_title': 'Home',
      'welcome_back': 'Welcome back',
      'profile_summary': 'Profile summary',
      'active_business_plan': 'Ready to start',
      'start_business_application': 'Start Business Application',
      'recent_searches': 'Recent searches',
      'no_recent_searches': 'No recent searches yet.',
      'no_business_started': 'No business plan started yet',
      'logout': 'Logout',
      'village': 'Village',
      'enter_village': 'Enter village',
      'block_mandal': 'Block / Mandal',
      'enter_block': 'Enter block / mandal',
      'district': 'District',
      'enter_district': 'Enter district',
      'location_title': 'Location',
      'margin_capital_title': 'Available Margin Capital',
      'how_much_contribute': 'How much money can you contribute?',
      'amount': 'Amount',
      'business_category_title': 'Business Category',
      'search_category': 'Search category',
      'review_title': 'YOUR BUSINESS PLAN',
      'available_margin': 'Available Margin',
      'business': 'Business',
      'language': 'Language',
      'edit': 'Edit',
      'confirm_continue': 'Confirm & Continue',
      'creating_application': 'Creating Application...',
      'error_creating': 'Unable to create your business application.',
      'retry': 'Retry',
      'success_created': 'Application created successfully! (ID: %s)',
      'scale_question_default': 'How big do you want to start your business?',
      'scale_helper_default': 'An approximate value is enough.',
      'scale_question_custom': 'How many customers do you expect per day?',
      'scale_question_dairy': 'How many animals do you plan to keep?',
      'scale_question_tailoring': 'How many clothes can you make per month?',
      'scale_question_retail': 'How much stock do you plan to start with?',
      'scale_question_food': 'How much can you produce in a month?',
      'scale_question_agri': 'How much can you handle in a month?',
      'scale_info_title': 'About this question',
      'scale_info_text': 'Don\'t worry if you\'re not sure. Give us your best estimate. An approximate value is enough, and the system will use it to estimate a suitable business size.',
      'scale_unknown': 'I don\'t know',
      'scale_unknown_message': 'That\'s okay. We can estimate a suitable starting scale for you.',
      'scale_validation_required': 'Please enter a number or choose "I don\'t know".',
      'scale_validation_invalid': 'Please enter a reasonable estimate.',
      'scale_suffix_customers': 'customers/day',
      'scale_suffix_animals': 'animals',
      'scale_suffix_clothes': 'clothes/month',
      'scale_suffix_stock': '₹ approx stock',
      'scale_suffix_kg': 'kg/month',
      'scale_suffix_litres': 'litres/month',
      'scale_suffix_acres': 'acres',
      'scale_hint_example': 'Example: 5',
      'cancel': 'Cancel',
      'no_business_types_available': 'No business types are available for this sector.',
      'choose_business_type': 'Choose a business type',
      'describe_custom_plan': 'Describe your custom plan',
      'custom_plan_hint': 'E.g., I want to start a 10 cow dairy farm...',
      'save': 'Save',
      'please_choose_valid_location': 'Please choose a valid location.',
      'required': 'Required',
      'financial_analysis_title': 'Financial Analysis',
      'calculating_your_plan': 'Calculating your financial plan...',
      'no_application_found': 'No application found. Please go back.',
      'unable_to_calculate_plan': 'Unable to calculate your financial plan.',
      'continue_to_scheme': 'Continue to Scheme',
      'back': 'Back',
      'unknown': 'Unknown',
      'financial_explanation': 'Financial Explanation',
      'listen_to_financial_summary': 'Listen to financial summary',
      'your_contribution': 'Your Contribution',
      'finding_suitable_scheme': 'Finding the most suitable funding scheme...',
      'unable_to_determine_scheme': 'Unable to determine the funding scheme.',
      'recommended_scheme': 'Your Recommended Scheme',
      'not_eligible': 'Not Eligible',
      'suitable_for_project': 'Suitable for your project',
      'loan_terms': 'Loan Terms',
      'why_this_scheme': 'Why this scheme?',
      'scheme_benefits': 'Scheme Benefits',
      'eligibility_warnings': 'Eligibility Warnings',
      'listen': 'Listen',
      'continue_to_market_analysis': 'Continue to Market Analysis',
      'scheme_result_eligible_description': 'Your project qualifies for this scheme.',
      'scheme_result_not_eligible_description': 'This project is not eligible for this scheme.',
      'final_dashboard_title': 'Final Dashboard',
      'business_feasibility_summary': 'BUSINESS FEASIBILITY SUMMARY',
      'ruralbiz_ai': 'RURALBIZ AI',
      'view_full_analysis': 'View Full Analysis',
      'financial_snapshot': 'FINANCIAL SNAPSHOT (Calculated)',
      'project_cost': 'Project Cost',
      'loan_requirement': 'Loan Requirement',
      'emi': 'EMI',
      'view_financial_analysis': 'View Financial Analysis',
      'scheme_label': 'SCHEME',
      'view_scheme': 'View Scheme',
      'local_market_estimated': 'LOCAL MARKET (Estimated)',
      'demand_index': 'Demand index',
      'competitors': 'Competitors',
      'market_opportunity': 'Market Opportunity',
      'view_market_analysis': 'View Market Analysis',
      'key_risks': 'KEY RISKS',
      'opportunities': 'OPPORTUNITIES',
      'business_decision': 'BUSINESS DECISION',
      'review_risks': 'Review Risks',
      'proceed': 'Proceed',
      'proceed_with_caution': 'Proceed with Caution',
      'not_recommended': 'Not Recommended',
      'ai_advisory': 'AI ADVISORY',
      'ask_ai_advisor': 'Ask AI Advisor',
      'ai_guidance_note': 'AI-generated guidance based on your RuralBiz AI analysis.',
      'report_generated_successfully': 'Report generated successfully!',
      'report_is_ready': 'Report is ready to share as PDF.',
      'share_pdf_report': 'Share PDF Report',
      'download_pdf': 'Download PDF',
      'generate_business_report': 'Generate Business Report',
      'view_report_details': 'View Report Details',
      'preparing_report': 'Preparing your business report...',
      'report_saved_to': 'PDF saved to %s',
      'overall_feasibility': 'OVERALL FEASIBILITY',
      'go_to_home': 'Go to Home',
      'feasibility_analysis_title': 'Feasibility Analysis',
      'your_business_feasibility': 'YOUR BUSINESS FEASIBILITY',
      'listen_to_summary': 'Listen to Summary',
      'evaluating_business': 'Evaluating your business...',
      'unable_feasibility_assessment': 'Unable to complete the feasibility assessment.',
      'market_gap': 'MARKET GAP',
      'analysis_incomplete': 'Analysis incomplete. Please complete previous phases first.',
      'start_application': 'Start Application',
      'home': 'Home',
    },
    'te': {
      'language_selection': 'భాషా ఎంపిక',
      'select_language': 'దయచేసి మీ భాషను ఎంచుకోండి',
      'next': 'తరువాత',
      'home_title': 'హోమ్',
      'welcome_back': 'మరలా స్వాగతం',
      'profile_summary': 'ప్రొఫైల్ సారాంశం',
      'active_business_plan': 'ప్రారంభించడానికి సిద్ధంగా ఉంది',
      'start_business_application': 'వ్యాపార దరఖాస్తును ప్రారంభించండి',
      'recent_searches': 'ఇటీవలి సెర్చ్లు',
      'no_recent_searches': 'ఇటీవలి సెర్చ్లు లేవు.',
      'no_business_started': 'వ్యాపార ప్రణాళిక ఇంకా ప్రారంభించబడలేదు',
      'logout': 'లాగ్అవుట్',
      'village': 'గ్రామం',
      'enter_village': 'గ్రామం నమోదు చేయండి',
      'block_mandal': 'బ్లాక్ / మండలం',
      'enter_block': 'బ్లాక్ / మండలం నమోదు చేయండి',
      'district': 'జిల్లా',
      'enter_district': 'జిల్లా నమోదు చేయండి',
      'location_title': 'స్థానం',
      'margin_capital_title': 'అందుబాటులో ఉన్న పెట్టుబడి',
      'how_much_contribute': 'మీరు ఎంత డబ్బు సమకూర్చగలరు?',
      'amount': 'మొత్తం',
      'business_category_title': 'వ్యాపార వర్గం',
      'search_category': 'వర్గాన్ని శోధించండి',
      'review_title': 'మీ వ్యాపార ప్రణాళిక',
      'available_margin': 'అందుబాటులో ఉన్న పెట్టుబడి',
      'business': 'వ్యాపారం',
      'language': 'భాష',
      'edit': 'సవరించు',
      'confirm_continue': 'నిర్ధారించండి & కొనసాగించండి',
      'creating_application': 'దరఖాస్తు సృష్టించబడుతోంది...',
      'error_creating': 'మీ వ్యాపార దరఖాస్తును సృష్టించడం సాధ్యపడలేదు.',
      'retry': 'మళ్లీ ప్రయత్నించండి',
      'success_created': 'దరఖాస్తు విజయవంతంగా సృష్టించబడింది! (ID: %s)',
      'scale_question_default': 'మీ వ్యాపారాన్ని ప్రారంభించడానికి మీరు ఎంత పెద్దదిగా అనుకుంటున్నారు?',
      'scale_helper_default': 'సుమారుగా ఇవ్వబడిన విలువ సరిపోతుంది.',
      'scale_question_custom': 'రోజుకు మీరు ఎన్ని కస్టమర్లను ఆశిస్తున్నారు?',
      'scale_question_dairy': 'మీరు ఎన్ని పశువులను పెట్టాలనుకుంటున్నారు?',
      'scale_question_tailoring': 'నెలకు మీరు ఎన్ని బట్టలు కుట్టగలరు?',
      'scale_question_retail': 'ప్రారంభంలో మీరు ఎంత స్టాక్ పెట్టాలనుకుంటున్నారు?',
      'scale_question_food': 'నెలకు మీరు ఎంత ఉత్పత్తి చేయగలరు?',
      'scale_question_agri': 'నెలకు మీరు ఎంత పని చేయగలరు?',
      'scale_info_title': 'ఈ ప్రశ్న గురించి',
      'scale_info_text': 'మీకు ఖచ్చితంగా తెలియకపోతే చింతించకండి. మీకు బాగా తెలిసిన అంచనాను ఇవ్వండి. సుమారుగా ఇవ్వబడిన విలువ సరిపోతుంది; సిస్టమ్ దాన్ని ఉపయోగించి సరిపోలే వ్యాపార పరిమాణాన్ని అంచనా వేస్తుంది.',
      'scale_unknown': 'నాకు తెలియదు',
      'scale_unknown_message': 'సరే. మేము మీకు సరిపోలే ప్రారంభ పరిమాణాన్ని అంచనా వేస్తాము.',
      'scale_validation_required': 'దయచేసి సంఖ్యను నమోదు చేయండి లేదా "నాకు తెలియదు" ఎంచుకోండి.',
      'scale_validation_invalid': 'దయచేసి సహేతుక అంచనాను నమోదు చేయండి.',
      'scale_suffix_customers': 'కస్టమర్లు/రోజు',
      'scale_suffix_animals': 'పశువులు',
      'scale_suffix_clothes': 'బట్టలు/నెల',
      'scale_suffix_stock': '₹ సుమారపు స్టాక్',
      'scale_suffix_kg': 'kg/నెల',
      'scale_suffix_litres': 'లీటర్లు/నెల',
      'scale_suffix_acres': 'ఎకరాలు',
      'scale_hint_example': 'ఉదాహరణ: 5',
      'cancel': 'రద్దు చేయండి',
      'no_business_types_available': 'ఈ సెక్షన్‌కి వ్యాపార రకాలు అందుబాటులో లేవు.',
      'choose_business_type': 'వ్యాపార రకాన్ని ఎంచుకోండి',
      'describe_custom_plan': 'మీ కస్టమ్ ప్లాన్‌ను వివరించండి',
      'custom_plan_hint': 'ఉదాహరణ: నేను 10 పశువుల పాలపోసే రైతు వ్యవసాయాన్ని ప్రారంభించాలనుకుంటున్నాను...',
      'save': 'సేవ్ చేయండి',
      'please_choose_valid_location': 'దయచేసి సరైన స్థలాన్ని ఎంచుకోండి.',
      'required': 'అవసరం',
      'financial_analysis_title': 'ఫైనాన్షియల్ అనాలిసిస్',
      'calculating_your_plan': 'మీ ఆర్థిక ప్రణాళికను గణిస్తోంది...',
      'no_application_found': 'దరఖాస్తు కనబడలేదు. దయచేసి వెనక్కి వెళ్లండి.',
      'unable_to_calculate_plan': 'మీ ఆర్థిక ప్రణాళికను గణించడం సాధ్యపడలేదు.',
      'continue_to_scheme': 'స్కీమ్‌కి కొనసాగించండి',
      'back': 'వెనుకకు',
      'business_summary': 'వ్యాపార సారాంశం',
      'business_label': 'వ్యాపారం',
      'your_contribution': 'మీ సహకారం',
      'location_label': 'స్థానం',
      'margin_capital_label': 'మార్జిన్ క్యాపిటల్',
      'unknown': 'తెలియదు',
      'financial_explanation': 'ఆర్థిక వివరణ',
      'listen_to_financial_summary': 'ఆర్థిక సారాంశాన్ని వినండి',
      'project_cost': 'ప్రాజెక్ట్ ఖర్చు',
      'maximum_loan': 'గరిష్ఠ లోన్',
      'interest_rate': 'వడ్డీ రేటు',
      'tenure': 'కాలవ్యవధి',
      'moratorium': 'మోరేటోరియం',
      'monthly_emi': 'మాసిక EMI',
      'quarterly': 'త్రైమాసికం',
      'finding_suitable_scheme': 'సరిపోలే ఫండింగ్ స్కీమ్‌ను కనుగొంటోంది...',
      'unable_to_determine_scheme': 'ఫండింగ్ స్కీమును నిర్ణయించడం సాధ్యపడలేదు.',
      'recommended_scheme': 'మీకు సిఫార్సు చేసిన స్కీమ్',
      'not_eligible': 'అర్హత లేదు',
      'suitable_for_project': 'మీ ప్రాజెక్టుకు సరిపోతుంది',
      'loan_terms': 'లోన్ షరతులు',
      'why_this_scheme': 'ఈ స్కీమ్ ఎందుకు?',
      'scheme_benefits': 'స్కీమ్ ప్రయోజనాలు',
      'eligibility_warnings': 'అర్హత హెచ్చరికలు',
      'listen': 'వినండి',
      'final_dashboard_title': 'చివరి డాష్‌బోర్డ్',
      'business_feasibility_summary': 'వ్యాపార సాధ్యత సారాంశం',
      'ruralbiz_ai': 'రూరల్‌బిజ్ AI',
      'overall_feasibility': 'మొత్తం సాధ్యత',
      'view_full_analysis': 'పూర్తి విశ్లేషణ చూడండి',
      'financial_snapshot': 'ఆర్థిక సారాంశం (గణించబడింది)',
      'scheme_label': 'స్కీమ్',
      'view_scheme': 'స్కీమ్ చూడండి',
      'local_market_estimated': 'స్థానిక మార్కెట్ (అంచనా)',
      'demand_index': 'డిమాండ్ ఇండెక్స్',
      'competitors': 'ప్రత్యర్థులు',
      'market_opportunity': 'మార్కెట్ అవకాశాలు',
      'view_market_analysis': 'మార్కెట్ విశ్లేషణ చూడండి',
      'key_risks': 'ముఖ్య ప్రమాదాలు',
      'opportunities': 'అవకాశాలు',
      'business_decision': 'వ్యాపార నిర్ణయం',
      'review_risks': 'ప్రమాదాలను పరిశీలించండి',
      'proceed': 'కొనసాగించండి',
      'proceed_with_caution': 'జాగ్రత్తగా కొనసాగించండి',
      'not_recommended': 'సిఫార్సు చేయబడలేదు',
      'ai_advisory': 'AI సలహా',
      'ask_ai_advisor': 'AI అడ్వైజర్‌ను అడగండి',
      'ai_guidance_note': 'మీ RuralBiz AI విశ్లేషణ ఆధారంగా AI రూపొందించిన మార్గదర్శకత్వం.',
      'report_generated_successfully': 'రిపోర్ట్ విజయవంతంగా రూపొందించబడింది!',
      'report_is_ready': 'రిపోర్ట్ PDF రూపంలో భాగస్వామ్యం కోసం సిద్ధంగా ఉంది.',
      'share_pdf_report': 'PDF రిపోర్ట్ షేర్ చేయండి',
      'download_pdf': 'PDF డౌన్‌లోడ్ చేయండి',
      'generate_business_report': 'వ్యాపార రిపోర్ట్ సృష్టించండి',
      'view_report_details': 'రిపోర్ట్ వివరాలు చూడండి',
      'preparing_report': 'మీ వ్యాపార రిపోర్ట్‌ను సిద్ధం చేస్తున్నారు...',
      'report_saved_to': 'PDF సేవ్ చేయబడింది: %s',
      'feasibility_analysis_title': 'సాధ్యత విశ్లేషణ',
      'your_business_feasibility': 'మీ వ్యాపార సాధ్యత',
      'listen_to_summary': 'సారాంశాన్ని వినండి',
      'evaluating_business': 'మీ వ్యాపారాన్ని అంచనా వేస్తున్నారు...',
      'unable_feasibility_assessment': 'సాధ్యత అంచనాను పూర్తి చేయడం సాధ్యపడలేదు.',
      'market_gap': 'మార్కెట్ గ్యాప్',
      'go_to_home': 'హోమ్‌కు వెళ్లండి',
      'analysis_incomplete': 'విశ్లేషణ అసంపూర్ణంగా ఉంది. ముందున్న దశలను పూర్తి చేయండి.',
      'start_application': 'దరఖాస్తును ప్రారంభించండి',
      'home': 'హోమ్',
    },
    'hi': {
      'language_selection': 'भाषा चयन',
      'select_language': 'कृपया अपनी भाषा चुनें',
      'next': 'अगला',
      'home_title': 'होम',
      'welcome_back': 'फिर से स्वागत है',
      'profile_summary': 'प्रोफ़ाइल सारांश',
      'active_business_plan': 'शुरू करने के लिए तैयार',
      'start_business_application': 'व्यवसाय आवेदन शुरू करें',
      'recent_searches': 'हाल की खोजें',
      'no_recent_searches': 'अभी कोई हाल की खोज नहीं है।',
      'no_business_started': 'अभी कोई व्यवसाय योजना शुरू नहीं हुई है',
      'logout': 'लॉग आउट',
      'village': 'गाँव',
      'enter_village': 'गाँव दर्ज करें',
      'block_mandal': 'ब्लॉक / मंडल',
      'enter_block': 'ब्लॉक / मंडल दर्ज करें',
      'district': 'ज़िला',
      'enter_district': 'ज़िला दर्ज करें',
      'location_title': 'स्थान',
      'margin_capital_title': 'उपलब्ध मार्जिन पूंजी',
      'how_much_contribute': 'आप कितना पैसा लगा सकते हैं?',
      'amount': 'राशि',
      'business_category_title': 'व्यापार श्रेणी',
      'search_category': 'श्रेणी खोजें',
      'review_title': 'आपकी व्यवसाय योजना',
      'available_margin': 'उपलब्ध मार्जिन',
      'business': 'व्यापार',
      'language': 'भाषा',
      'edit': 'संपादित करें',
      'confirm_continue': 'पुष्टि करें और जारी रखें',
      'creating_application': 'एप्लिकेशन बनाया जा रहा है...',
      'error_creating': 'आपका व्यवसाय एप्लिकेशन बनाने में असमर्थ।',
      'retry': 'पुनः प्रयास करें',
      'success_created': 'एप्लिकेशन सफलतापूर्वक बनाया गया! (ID: %s)',
      'scale_question_default': 'आप अपनी व्यावसायिक शुरुआत कितनी बड़ी करना चाहते हैं?',
      'scale_helper_default': 'लगभग सही मान पर्याप्त है।',
      'scale_question_custom': 'आप रोज़ कितने ग्राहकों की उम्मीद करते हैं?',
      'scale_question_dairy': 'आप कितने पशु रखना चाहते हैं?',
      'scale_question_tailoring': 'आप महीने में कितने कपड़े बना सकते हैं?',
      'scale_question_retail': 'आप शुरुआत में कितना स्टॉक रखना चाहते हैं?',
      'scale_question_food': 'आप महीने में कितना उत्पादन कर सकते हैं?',
      'scale_question_agri': 'आप महीने में कितना काम संभाल सकते हैं?',
      'scale_info_title': 'इस प्रश्न के बारे में',
      'scale_info_text': 'अगर आपको पता न हो तो चिंता न करें। अपना सबसे अच्छा अनुमान दें। लगभग सही मान पर्याप्त है, और सिस्टम उसी के आधार पर उपयुक्त व्यवसाय का आकार приблизित करेगा।',
      'scale_unknown': 'मुझे पता नहीं',
      'scale_unknown_message': 'ठीक है। हम आपके लिए एक उपयुक्त शुरुआती आकार अनुमानित करेंगे।',
      'scale_validation_required': 'कृपया नंबर दर्ज करें या "मुझे पता नहीं" चुनें।',
      'scale_validation_invalid': 'कृपया एक उचित अनुमान दर्ज करें।',
      'scale_suffix_customers': 'ग्राहक/दिन',
      'scale_suffix_animals': 'पशु',
      'scale_suffix_clothes': 'कपड़े/माह',
      'scale_suffix_stock': '₹ लगभग स्टॉक',
      'scale_suffix_kg': 'kg/माह',
      'scale_suffix_litres': 'लीटर/माह',
      'scale_suffix_acres': 'एकड़',
      'scale_hint_example': 'उदाहरण: 5',
      'cancel': 'रद्द करें',
      'no_business_types_available': 'इस क्षेत्र के लिए कोई व्यवसाय प्रकार उपलब्ध नहीं है।',
      'choose_business_type': 'व्यवसाय प्रकार चुनें',
      'describe_custom_plan': 'अपना कस्टम प्लान बताएं',
      'custom_plan_hint': 'उदाहरण: मैं 10 गायों के साथ डेयरी शुरू करना चाहता हूँ...',
      'save': 'सेव करें',
      'please_choose_valid_location': 'कृपया सही स्थान चुनें।',
      'required': 'आवश्यक',
      'financial_analysis_title': 'वित्तीय विश्लेषण',
      'calculating_your_plan': 'आपका वित्तीय प्लान गणना हो रहा है...',
      'no_application_found': 'कोई एप्लिकेशन नहीं मिला। कृपया वापस जाएँ।',
      'unable_to_calculate_plan': 'आपका वित्तीय प्लान गणना करने में असमर्थ।',
      'continue_to_scheme': 'स्कीम पर जारी रखें',
      'back': 'वापस',
      'business_summary': 'व्यवसाय सारांश',
      'business_label': 'व्यवसाय',
      'your_contribution': 'आपका योगदान',
      'location_label': 'स्थान',
      'margin_capital_label': 'मार्जिन पूंजी',
      'unknown': 'अज्ञात',
      'financial_explanation': 'वित्तीय विवरण',
      'listen_to_financial_summary': 'वित्तीय सारांश सुनें',
      'project_cost': 'प्रोजेक्ट लागत',
      'maximum_loan': 'अधिकतम ऋण',
      'interest_rate': 'ब्याज दर',
      'tenure': 'अवधि',
      'moratorium': 'मोराटोरियम',
      'monthly_emi': 'मासिक EMI',
      'quarterly': 'त्रैमासिक',
      'finding_suitable_scheme': 'सबसे उपयुक्त फंडिंग स्कीम ढूंढी जा रही है...',
      'unable_to_determine_scheme': 'फंडिंग स्कीम निर्धारित नहीं की जा सकती।',
      'recommended_scheme': 'आपके लिए सिफारिश की गई स्कीम',
      'not_eligible': 'अर्ह नहीं',
      'suitable_for_project': 'आपके प्रोजेक्ट के लिए उपयुक्त',
      'loan_terms': 'ऋण शर्तें',
      'why_this_scheme': 'यह स्कीम क्यों?',
      'scheme_benefits': 'स्कीम लाभ',
      'eligibility_warnings': 'अर्हता चेतावनियाँ',
      'listen': 'सुनें',
      'final_dashboard_title': 'अंतिम डैशबोर्ड',
      'business_feasibility_summary': 'व्यवसाय व्यवहार्यता सारांश',
      'ruralbiz_ai': 'रूरलबिज़ AI',
      'overall_feasibility': 'कुल व्यवहार्यता',
      'view_full_analysis': 'पूरा विश्लेषण देखें',
      'financial_snapshot': 'वित्तीय सारांश (गणना किया गया)',
      'scheme_label': 'स्कीम',
      'view_scheme': 'स्कीम देखें',
      'local_market_estimated': 'स्थानीय बाजार (अनुमानित)',
      'demand_index': 'मांग इंडेक्स',
      'competitors': 'प्रतिद्वंद्वी',
      'market_opportunity': 'बाजार अवसर',
      'view_market_analysis': 'बाजार विश्लेषण देखें',
      'key_risks': 'मुख्य जोखिम',
      'opportunities': 'अवसर',
      'business_decision': 'व्यवसाय निर्णय',
      'review_risks': 'जोखिम देखें',
      'proceed': 'आगे बढ़ें',
      'proceed_with_caution': 'सावधानी से आगे बढ़ें',
      'not_recommended': 'अनुशंसित नहीं',
      'ai_advisory': 'AI सलाह',
      'ask_ai_advisor': 'AI सलाहकार से पूछें',
      'ai_guidance_note': 'आपके RuralBiz AI विश्लेषण के आधार पर AI द्वारा तैयार मार्गदर्शिका।',
      'report_generated_successfully': 'रिपोर्ट सफलतापूर्वक तैयार हो गई!',
      'report_is_ready': 'रिपोर्ट PDF के रूप में साझा करने के लिए तैयार है।',
      'share_pdf_report': 'PDF रिपोर्ट साझा करें',
      'download_pdf': 'PDF डाउनलोड करें',
      'generate_business_report': 'व्यवसाय रिपोर्ट बनाएं',
      'view_report_details': 'रिपोर्ट विवरण देखें',
      'preparing_report': 'आपकी व्यवसाय रिपोर्ट तैयार की जा रही है...',
      'report_saved_to': 'PDF सेव हो गया: %s',
      'feasibility_analysis_title': 'व्यवहार्यता विश्लेषण',
      'your_business_feasibility': 'आपकी व्यवसाय व्यवहार्यता',
      'listen_to_summary': 'सारांश सुनें',
      'evaluating_business': 'आपके व्यवसाय का मूल्यांकन किया जा रहा है...',
      'unable_feasibility_assessment': 'व्यवहार्यता मूल्यांकन पूरा नहीं किया जा सका।',
      'market_gap': 'बाजार अंतर',
      'go_to_home': 'होम पर जाएँ',
      'analysis_incomplete': 'विश्लेषण अधूरा है। कृपया पहले की प्रक्रियाएँ पूरी करें।',
      'start_application': 'आवेदन शुरू करें',
      'home': 'होम',
    }
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'te', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
